/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ywl5320_ffmpegpro_FFmplayer */

#ifndef _Included_com_ywl5320_ffmpegpro_FFmplayer
#define _Included_com_ywl5320_ffmpegpro_FFmplayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ywl5320_ffmpegpro_FFmplayer
 * Method:    showFFmpegInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ywl5320_ffmpegpro_FFmplayer_showFFmpegInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
